-- 100 dummy employees (password: Employee123!)
INSERT INTO users (id, full_name, email, position, password_hash, is_active)
VALUES
  (gen_random_uuid(), 'Adi Kurniawan',       'adi.kurniawan@company.com',       'Data Analyst',                '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Agus Setiawan',       'agus.setiawan@company.com',       'Senior Data Engineer',        '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Andi Firmansyah',     'andi.firmansyah@company.com',     'Business Analyst',            '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Anton Hidayat',       'anton.hidayat@company.com',       'Software Engineer',           '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Arief Wibowo',        'arief.wibowo@company.com',        'DevOps Engineer',             '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Arif Nugroho',        'arif.nugroho@company.com',        'Data Scientist',              '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Bambang Susanto',     'bambang.susanto@company.com',     'IT Manager',                  '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Benny Hartono',       'benny.hartono@company.com',       'Solutions Architect',         '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Cahyo Prabowo',       'cahyo.prabowo@company.com',       'Backend Developer',           '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Dani Wahyudi',        'dani.wahyudi@company.com',        'Data Quality Analyst',        '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'David Santoso',       'david.santoso@company.com',       'Senior Data Analyst',         '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Dedi Prasetyo',       'dedi.prasetyo@company.com',       'System Analyst',              '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Denny Saputra',       'denny.saputra@company.com',       'Cloud Engineer',              '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Dimas Ramadhan',      'dimas.ramadhan@company.com',      'Data Engineer',               '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Fajar Maulana',       'fajar.maulana@company.com',       'QA Engineer',                 '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Fandi Kurnia',        'fandi.kurnia@company.com',        'Product Manager',             '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Febri Andriyanto',    'febri.andriyanto@company.com',    'Full Stack Developer',        '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Galih Permana',       'galih.permana@company.com',       'Database Administrator',      '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Gunawan Hidayatullah','gunawan.hidayatullah@company.com','Senior Software Engineer',    '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Hadi Subagyo',        'hadi.subagyo@company.com',        'IT Consultant',               '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Hendra Wijaya',       'hendra.wijaya@company.com',       'Data Governance Analyst',     '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Herman Sanjaya',      'herman.sanjaya@company.com',      'Risk Analyst',                '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Ibnu Hakim',          'ibnu.hakim@company.com',          'Compliance Officer',          '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Imam Wahyono',        'imam.wahyono@company.com',        'Scrum Master',                '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Iwan Setiadi',        'iwan.setiadi@company.com',        'Senior Business Analyst',     '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Joko Widiantoro',     'joko.widiantoro@company.com',     'Data Analyst',                '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Kevin Prasetya',      'kevin.prasetya@company.com',      'Frontend Developer',          '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Luthfi Hamdani',      'luthfi.hamdani@company.com',      'Senior Data Scientist',       '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Mahendra Kusuma',     'mahendra.kusuma@company.com',     'Data Engineer',               '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Muhammad Rizky',      'muhammad.rizky@company.com',      'Software Engineer',           '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Nanang Supriyadi',    'nanang.supriyadi@company.com',    'IT Consultant',               '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Pandu Wiradinata',    'pandu.wiradinata@company.com',    'Senior Project Manager',      '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Panji Adiputra',      'panji.adiputra@company.com',      'Cloud Engineer',              '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Rahmat Hidayat',      'rahmat.hidayat@company.com',      'Metadata Analyst',            '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Raka Pratama',        'raka.pratama@company.com',        'Data Quality Analyst',        '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Randi Firmanto',      'randi.firmanto@company.com',      'Backend Developer',           '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Rangga Satria',       'rangga.satria@company.com',       'DevOps Engineer',             '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Rendi Cahyono',       'rendi.cahyono@company.com',       'System Analyst',              '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Reza Fauzan',         'reza.fauzan@company.com',         'Senior Data Engineer',        '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Rifki Maulana',       'rifki.maulana@company.com',       'Data Scientist',              '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Rio Harianto',        'rio.harianto@company.com',        'QA Engineer',                 '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Ryan Budiman',        'ryan.budiman@company.com',        'Full Stack Developer',        '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Satria Nugroho',      'satria.nugroho@company.com',      'Solutions Architect',         '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Sigit Prayogo',       'sigit.prayogo@company.com',       'Senior Business Analyst',     '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Sugeng Raharjo',      'sugeng.raharjo@company.com',      'Database Administrator',      '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Surya Kusuma',        'surya.kusuma@company.com',        'IT Manager',                  '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Teguh Santoso',       'teguh.santoso@company.com',       'Risk Analyst',                '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Tommy Wirabuana',     'tommy.wirabuana@company.com',     'Product Manager',             '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Umar Hakim',          'umar.hakim@company.com',          'Compliance Officer',          '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Wahyu Setiawan',      'wahyu.setiawan@company.com',      'Data Governance Analyst',     '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Wisnu Wardhana',      'wisnu.wardhana@company.com',      'Senior Software Engineer',    '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Yogi Pratama',        'yogi.pratama@company.com',        'Data Analyst',                '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Yudi Santosa',        'yudi.santosa@company.com',        'Scrum Master',                '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Yusuf Rachman',       'yusuf.rachman@company.com',       'Frontend Developer',          '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  -- Female employees
  (gen_random_uuid(), 'Aini Rahmawati',      'aini.rahmawati@company.com',      'Data Analyst',                '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Amalia Putri',        'amalia.putri@company.com',        'Business Analyst',            '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Anastasia Dewi',      'anastasia.dewi@company.com',      'Senior Data Analyst',         '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Aulia Rahma',         'aulia.rahma@company.com',         'Data Scientist',              '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Ayu Lestari',         'ayu.lestari@company.com',         'Compliance Officer',          '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Bunga Pertiwi',       'bunga.pertiwi@company.com',       'QA Engineer',                 '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Citra Nirmala',       'citra.nirmala@company.com',       'Product Manager',             '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Desi Wulandari',      'desi.wulandari@company.com',      'Data Quality Analyst',        '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Diah Ayu Ningrum',    'diah.ayu@company.com',            'Metadata Analyst',            '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Diana Puspita',       'diana.puspita@company.com',       'Senior Business Analyst',     '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Dina Marliana',       'dina.marliana@company.com',       'Risk Analyst',                '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Endah Sulistyowati',  'endah.sulistyowati@company.com',  'Data Governance Analyst',     '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Eva Kristina',        'eva.kristina@company.com',        'Software Engineer',           '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Fani Oktavia',        'fani.oktavia@company.com',        'IT Consultant',               '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Fatimah Zahra',       'fatimah.zahra@company.com',       'Compliance Officer',          '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Febby Anggraini',     'febby.anggraini@company.com',     'Data Engineer',               '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Hani Setyaningsih',   'hani.setyaningsih@company.com',   'Senior Data Engineer',        '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Indah Permatasari',   'indah.permatasari@company.com',   'Business Analyst',            '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Intan Novitasari',    'intan.novitasari@company.com',    'Data Scientist',              '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Ira Sukmawati',       'ira.sukmawati@company.com',       'Senior Data Scientist',       '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Kartika Sari',        'kartika.sari@company.com',        'Project Manager',             '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Laila Nurhayati',     'laila.nurhayati@company.com',     'System Analyst',              '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Lestari Handayani',   'lestari.handayani@company.com',   'Data Quality Analyst',        '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Lina Marlina',        'lina.marlina@company.com',        'Frontend Developer',          '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Maya Sofianti',       'maya.sofianti@company.com',       'Senior Software Engineer',    '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Mega Wulandari',      'mega.wulandari@company.com',      'Scrum Master',                '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Mila Agustina',       'mila.agustina@company.com',       'Data Analyst',                '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Nabila Azzahra',      'nabila.azzahra@company.com',      'Data Governance Analyst',     '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Nadia Rahmatika',     'nadia.rahmatika@company.com',     'IT Manager',                  '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Novi Andriani',       'novi.andriani@company.com',       'Backend Developer',           '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Nurul Hidayah',       'nurul.hidayah@company.com',       'Metadata Analyst',            '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Putri Rahayu',        'putri.rahayu@company.com',        'Cloud Engineer',              '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Ratna Dewi',          'ratna.dewi@company.com',          'Solutions Architect',         '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Reni Oktaviani',      'reni.oktaviani@company.com',      'Full Stack Developer',        '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Rina Puspitasari',    'rina.puspitasari@company.com',    'Risk Analyst',                '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Risma Nurul Aini',    'risma.nurul@company.com',         'QA Engineer',                 '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Sari Wahyuningsih',   'sari.wahyuningsih@company.com',   'Database Administrator',      '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Sella Oktaviani',     'sella.oktaviani@company.com',     'IT Consultant',               '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Shinta Kusumawati',   'shinta.kusumawati@company.com',   'Senior Project Manager',      '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Sri Wahyuni',         'sri.wahyuni@company.com',         'Data Engineer',               '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Suci Ramadhani',      'suci.ramadhani@company.com',      'Senior Data Analyst',         '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Syifa Aulia',         'syifa.aulia@company.com',         'Compliance Officer',          '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Tania Putri',         'tania.putri@company.com',         'Product Manager',             '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Umi Kalsum',          'umi.kalsum@company.com',          'Data Quality Analyst',        '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Vina Oktavia',        'vina.oktavia@company.com',        'DevOps Engineer',             '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Winda Sari',          'winda.sari@company.com',          'Data Scientist',              '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Wulan Dari',          'wulan.dari@company.com',          'Software Engineer',           '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Yeni Marlina',        'yeni.marlina@company.com',        'Metadata Analyst',            '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Yuli Astuti',         'yuli.astuti@company.com',         'Senior Data Engineer',        '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true),
  (gen_random_uuid(), 'Yunita Sari',         'yunita.sari@company.com',         'Data Governance Analyst',     '$2b$12$G63eWZaFuQHhJNmA5VutW.heWhO6/NTii.wajqafDDloK6B1Vabve', true)
ON CONFLICT (email) DO NOTHING;
