"""add_notifications

Revision ID: 312dcd0ffeaf
Revises: 001
Create Date: 2026-05-04 14:32:25.154324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '312dcd0ffeaf'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bapd_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bapd_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('approver_role', sa.String(length=60), nullable=False),
    sa.Column('step_order', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_bapd_approvals_approver_id_users')),
    sa.ForeignKeyConstraint(['bapd_id'], ['bapd_records.id'], name=op.f('fk_bapd_approvals_bapd_id_bapd_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bapd_approvals'))
    )
    op.create_index(op.f('ix_bapd_approvals_bapd_id'), 'bapd_approvals', ['bapd_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=60), nullable=False),
    sa.Column('event', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_module', 'notifications', ['module'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=60), nullable=False),
    sa.Column('in_app', sa.Boolean(), nullable=False),
    sa.Column('email', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_preferences_user_id', 'notification_preferences', ['user_id'], unique=False)
    op.alter_column('ai_compliance_checklists', 'fairness_ok',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_compliance_checklists', 'minimization_ok',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_compliance_checklists', 'explainability_ok',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_ai_checklist_dsr_id'), 'ai_compliance_checklists', type_='unique')
    op.create_unique_constraint(op.f('uq_ai_compliance_checklists_dsr_id'), 'ai_compliance_checklists', ['dsr_id'])
    op.alter_column('audit_logs', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('audit_logs', 'module',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.drop_constraint(op.f('fk_audit_logs_user_id'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_logs_user_id_users'), 'audit_logs', 'users', ['user_id'], ['id'])
    op.alter_column('bapd_records', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bapd_records', 'version',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_bapd_project_id'), table_name='bapd_records')
    op.drop_index(op.f('ix_bapd_status'), table_name='bapd_records')
    op.create_index(op.f('ix_bapd_records_project_id'), 'bapd_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_bapd_records_status'), 'bapd_records', ['status'], unique=False)
    op.drop_index(op.f('ix_dos_project_id'), table_name='data_owner_stewards')
    op.create_index(op.f('ix_data_owner_stewards_project_id'), 'data_owner_stewards', ['project_id'], unique=False)
    op.alter_column('data_sharing_requests', 'is_ai_use',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('data_sharing_requests', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_dsr_project_id'), table_name='data_sharing_requests')
    op.drop_index(op.f('ix_dsr_status'), table_name='data_sharing_requests')
    op.drop_index(op.f('ix_dsr_tracking_id'), table_name='data_sharing_requests')
    op.drop_constraint(op.f('uq_dsr_tracking_id'), 'data_sharing_requests', type_='unique')
    op.create_index(op.f('ix_data_sharing_requests_project_id'), 'data_sharing_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_data_sharing_requests_status'), 'data_sharing_requests', ['status'], unique=False)
    op.create_index(op.f('ix_data_sharing_requests_tracking_id'), 'data_sharing_requests', ['tracking_id'], unique=True)
    op.alter_column('dpia_records', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dpia_records', 'version',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_dpia_project_id'), table_name='dpia_records')
    op.drop_index(op.f('ix_dpia_status'), table_name='dpia_records')
    op.create_index(op.f('ix_dpia_records_project_id'), 'dpia_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_dpia_records_status'), 'dpia_records', ['status'], unique=False)
    op.alter_column('dq_findings', 'severity',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dq_findings', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dq_gcp_archives', 'archive_status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dq_runs', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dq_runs', 'total_checks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dq_runs', 'passed_checks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dq_runs', 'failed_checks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dsr_approvals', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('metadata_records', 'table_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('metadata_records', 'data_sensitivity',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('metadata_records', 'definition_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('metadata_records', 'data_level',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('metadata_records', 'remarks',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_metadata_data_attribute'), table_name='metadata_records')
    op.drop_index(op.f('ix_metadata_data_domain_table'), table_name='metadata_records')
    op.drop_index(op.f('ix_metadata_project_id'), table_name='metadata_records')
    op.create_index(op.f('ix_metadata_records_data_attribute'), 'metadata_records', ['data_attribute'], unique=False)
    op.create_index(op.f('ix_metadata_records_data_domain_table'), 'metadata_records', ['data_domain_table'], unique=False)
    op.create_index(op.f('ix_metadata_records_project_id'), 'metadata_records', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('customer_name', sa.String(length=200), nullable=False))
    op.add_column('projects', sa.Column('line_of_business', sa.String(length=200), nullable=True))
    op.add_column('projects', sa.Column('use_case', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('project_year', sa.SmallInteger(), nullable=False))
    op.add_column('projects', sa.Column('project_category', sa.String(length=50), nullable=False))
    op.add_column('projects', sa.Column('is_monetized', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('delivery_manager_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('project_manager_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('dgo_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('metadata_officer_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('dq_officer_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('pic_data_compliance_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_constraint(op.f('uq_projects_project_code'), 'projects', type_='unique')
    op.create_index(op.f('ix_projects_customer_name'), 'projects', ['customer_name'], unique=False)
    op.create_index(op.f('ix_projects_project_year'), 'projects', ['project_year'], unique=False)
    op.drop_constraint(op.f('fk_projects_dq_officer'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_projects_project_manager'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_projects_pic_data_compliance'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_projects_metadata_officer'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_projects_dgo'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_projects_delivery_manager'), 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_projects_dq_officer_id_users'), 'projects', 'users', ['dq_officer_id'], ['id'])
    op.create_foreign_key(op.f('fk_projects_pic_data_compliance_id_users'), 'projects', 'users', ['pic_data_compliance_id'], ['id'])
    op.create_foreign_key(op.f('fk_projects_dgo_id_users'), 'projects', 'users', ['dgo_id'], ['id'])
    op.create_foreign_key(op.f('fk_projects_delivery_manager_id_users'), 'projects', 'users', ['delivery_manager_id'], ['id'])
    op.create_foreign_key(op.f('fk_projects_project_manager_id_users'), 'projects', 'users', ['project_manager_id'], ['id'])
    op.create_foreign_key(op.f('fk_projects_metadata_officer_id_users'), 'projects', 'users', ['metadata_officer_id'], ['id'])
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'delivery_manager')
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'dq_officer')
    op.drop_column('projects', 'data_governance_officer')
    op.drop_column('projects', 'project_code')
    op.drop_column('projects', 'metadata_officer')
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'pic_data_compliance')
    op.drop_column('projects', 'project_manager')
    op.drop_column('projects', 'status')
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('ropa_records', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ropa_records', 'version',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_ropa_project_id'), table_name='ropa_records')
    op.drop_index(op.f('ix_ropa_status'), table_name='ropa_records')
    op.create_index(op.f('ix_ropa_records_project_id'), 'ropa_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_ropa_records_status'), 'ropa_records', ['status'], unique=False)
    op.drop_index(op.f('ix_upr_project_id'), table_name='user_project_roles')
    op.drop_index(op.f('ix_upr_user_id'), table_name='user_project_roles')
    op.create_index(op.f('ix_user_project_roles_user_id'), 'user_project_roles', ['user_id'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_project_roles_user_id'), table_name='user_project_roles')
    op.create_index(op.f('ix_upr_user_id'), 'user_project_roles', ['user_id'], unique=False)
    op.create_index(op.f('ix_upr_project_id'), 'user_project_roles', ['project_id'], unique=False)
    op.drop_index(op.f('ix_ropa_records_status'), table_name='ropa_records')
    op.drop_index(op.f('ix_ropa_records_project_id'), table_name='ropa_records')
    op.create_index(op.f('ix_ropa_status'), 'ropa_records', ['status'], unique=False)
    op.create_index(op.f('ix_ropa_project_id'), 'ropa_records', ['project_id'], unique=False)
    op.alter_column('ropa_records', 'version',
               existing_type=sa.SMALLINT(),
               server_default=sa.text("'1'::smallint"),
               existing_nullable=False)
    op.alter_column('ropa_records', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'draft'::character varying"),
               existing_nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.add_column('projects', sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('project_manager', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('pic_data_compliance', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('metadata_officer', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('project_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('data_governance_officer', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('dq_officer', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('delivery_manager', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_projects_metadata_officer_id_users'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_projects_project_manager_id_users'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_projects_delivery_manager_id_users'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_projects_dgo_id_users'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_projects_pic_data_compliance_id_users'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_projects_dq_officer_id_users'), 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_projects_delivery_manager'), 'projects', 'users', ['delivery_manager'], ['id'])
    op.create_foreign_key(op.f('fk_projects_dgo'), 'projects', 'users', ['data_governance_officer'], ['id'])
    op.create_foreign_key(op.f('fk_projects_metadata_officer'), 'projects', 'users', ['metadata_officer'], ['id'])
    op.create_foreign_key(op.f('fk_projects_pic_data_compliance'), 'projects', 'users', ['pic_data_compliance'], ['id'])
    op.create_foreign_key(op.f('fk_projects_project_manager'), 'projects', 'users', ['project_manager'], ['id'])
    op.create_foreign_key(op.f('fk_projects_dq_officer'), 'projects', 'users', ['dq_officer'], ['id'])
    op.drop_index(op.f('ix_projects_project_year'), table_name='projects')
    op.drop_index(op.f('ix_projects_customer_name'), table_name='projects')
    op.create_unique_constraint(op.f('uq_projects_project_code'), 'projects', ['project_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.drop_column('projects', 'pic_data_compliance_id')
    op.drop_column('projects', 'dq_officer_id')
    op.drop_column('projects', 'metadata_officer_id')
    op.drop_column('projects', 'dgo_id')
    op.drop_column('projects', 'project_manager_id')
    op.drop_column('projects', 'delivery_manager_id')
    op.drop_column('projects', 'is_monetized')
    op.drop_column('projects', 'project_category')
    op.drop_column('projects', 'project_year')
    op.drop_column('projects', 'use_case')
    op.drop_column('projects', 'line_of_business')
    op.drop_column('projects', 'customer_name')
    op.drop_index(op.f('ix_metadata_records_project_id'), table_name='metadata_records')
    op.drop_index(op.f('ix_metadata_records_data_domain_table'), table_name='metadata_records')
    op.drop_index(op.f('ix_metadata_records_data_attribute'), table_name='metadata_records')
    op.create_index(op.f('ix_metadata_project_id'), 'metadata_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_metadata_data_domain_table'), 'metadata_records', ['data_domain_table'], unique=False)
    op.create_index(op.f('ix_metadata_data_attribute'), 'metadata_records', ['data_attribute'], unique=False)
    op.alter_column('metadata_records', 'remarks',
               existing_type=sa.TEXT(),
               server_default=sa.text("'-'::text"),
               existing_nullable=False)
    op.alter_column('metadata_records', 'data_level',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'Raw'::character varying"),
               existing_nullable=False)
    op.alter_column('metadata_records', 'definition_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('metadata_records', 'data_sensitivity',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'Confidential'::character varying"),
               existing_nullable=False)
    op.alter_column('metadata_records', 'table_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Source'::character varying"),
               existing_nullable=False)
    op.alter_column('dsr_approvals', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('dq_runs', 'failed_checks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('dq_runs', 'passed_checks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('dq_runs', 'total_checks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('dq_runs', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('dq_gcp_archives', 'archive_status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('dq_findings', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=False)
    op.alter_column('dq_findings', 'severity',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'warning'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_dpia_records_status'), table_name='dpia_records')
    op.drop_index(op.f('ix_dpia_records_project_id'), table_name='dpia_records')
    op.create_index(op.f('ix_dpia_status'), 'dpia_records', ['status'], unique=False)
    op.create_index(op.f('ix_dpia_project_id'), 'dpia_records', ['project_id'], unique=False)
    op.alter_column('dpia_records', 'version',
               existing_type=sa.SMALLINT(),
               server_default=sa.text("'1'::smallint"),
               existing_nullable=False)
    op.alter_column('dpia_records', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'draft'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_data_sharing_requests_tracking_id'), table_name='data_sharing_requests')
    op.drop_index(op.f('ix_data_sharing_requests_status'), table_name='data_sharing_requests')
    op.drop_index(op.f('ix_data_sharing_requests_project_id'), table_name='data_sharing_requests')
    op.create_unique_constraint(op.f('uq_dsr_tracking_id'), 'data_sharing_requests', ['tracking_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_dsr_tracking_id'), 'data_sharing_requests', ['tracking_id'], unique=False)
    op.create_index(op.f('ix_dsr_status'), 'data_sharing_requests', ['status'], unique=False)
    op.create_index(op.f('ix_dsr_project_id'), 'data_sharing_requests', ['project_id'], unique=False)
    op.alter_column('data_sharing_requests', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'draft'::character varying"),
               existing_nullable=False)
    op.alter_column('data_sharing_requests', 'is_ai_use',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_data_owner_stewards_project_id'), table_name='data_owner_stewards')
    op.create_index(op.f('ix_dos_project_id'), 'data_owner_stewards', ['project_id'], unique=False)
    op.drop_index(op.f('ix_bapd_records_status'), table_name='bapd_records')
    op.drop_index(op.f('ix_bapd_records_project_id'), table_name='bapd_records')
    op.create_index(op.f('ix_bapd_status'), 'bapd_records', ['status'], unique=False)
    op.create_index(op.f('ix_bapd_project_id'), 'bapd_records', ['project_id'], unique=False)
    op.alter_column('bapd_records', 'version',
               existing_type=sa.SMALLINT(),
               server_default=sa.text("'1'::smallint"),
               existing_nullable=False)
    op.alter_column('bapd_records', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'draft'::character varying"),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_audit_logs_user_id_users'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_logs_user_id'), 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('audit_logs', 'module',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('uq_ai_compliance_checklists_dsr_id'), 'ai_compliance_checklists', type_='unique')
    op.create_unique_constraint(op.f('uq_ai_checklist_dsr_id'), 'ai_compliance_checklists', ['dsr_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ai_compliance_checklists', 'explainability_ok',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('ai_compliance_checklists', 'minimization_ok',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('ai_compliance_checklists', 'fairness_ok',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_table('sales',
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('product_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('sale_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('sales_customer_id_fkey')),
    sa.PrimaryKeyConstraint('sale_id', name=op.f('sales_pkey'))
    )
    op.create_table('customer',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('registration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('segment', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('customer_pkey'))
    )
    op.drop_index('ix_notification_preferences_user_id', table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_module', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_bapd_approvals_bapd_id'), table_name='bapd_approvals')
    op.drop_table('bapd_approvals')
    # ### end Alembic commands ###
